### ISSUE TITLE
老哥找工作不？

### ISSUE THREAD

**Issue by markqq** [yefuyou/sparrow#1]
👋 你好，我们是阿里巴巴-大淘宝-直播技术前端团队，不知道您近期是否有求职意向？欢迎联系做进一步沟通：[tanpengcheng.tpc@alibaba-inc.com](mailto:tanpengcheng.tpc@alibaba-inc.com)

**Comment by yefuyou** [comment]
24届小菜狗，流程被卡在菜鸟噜<微笑>又不给发面试又不给进其他流程

**Comment by markqq** [comment]
能操作转 BU。有意向邮件联系哦，部门支招，随时跟进度
